name: Docker Build and Release
on: [ push ]
env:
#### An dieser Stelle müssen eure persönlichen Umgebungsvariablen eingetragen werden
  # Tipp: Die Token/der API-Key werden als Secrets in den Repository-Settings eingetragen und hier referenziert.
  GITHUB_ACCESSTOKEN: ${{ secrets.PETCLINICMH }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        cache: maven
  
    - name: Compile, build and push
      run: |
        #### AUFGABE COMPILE, DOCKER BUILD UND PUSH
        mvn package && docker build -t ghcr.io/woodapples/pet-clinic:latest -f Dockerfile .
        echo Maven und Docker Build
        docker login --username woodapples --password $GITHUB_ACCESSTOCKEN ghcr.io
        docker push ghcr.io/woodapples/pet-clinic:latest
        
        
